import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using Maqraa.",
};

const UPDATED = "26 June 2026";
const CONTACT = "faysalrulz123@gmail.com";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12">
      <Link href="/" className="text-sm font-semibold text-fg-muted hover:text-fg">
        ← Maqraa
      </Link>
      <h1 className="mt-4 font-serif text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-1 text-sm text-fg-muted">Last updated {UPDATED}</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-fg">
        <p className="rounded-xl bg-surface p-4 text-fg-muted ring-1 ring-border">
          This is a starting template. Have it reviewed by a qualified professional before relying
          on it for a public launch.
        </p>

        <Section title="Using Maqraa">
          <p>
            By creating an account you agree to these terms. You must be old enough to consent to
            this agreement in your country, or have a parent/guardian&apos;s permission.
          </p>
        </Section>

        <Section title="Your content and uploads">
          <p>
            Maqraa lets you upload books to read privately. You are responsible for the content you
            upload and confirm you have the right to use it. Do not upload material you are not
            permitted to copy. Uploaded books are private to your account; the curated catalogue is
            limited to public-domain and original works.
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Translations, quizzes, and comprehension tests are generated by AI and may contain
            errors. They are a learning aid, not an authoritative reference. Do not rely on them for
            anything where accuracy is critical.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>
            Don&apos;t abuse the service: no attempts to break, overload, or reverse-engineer it, and
            no uploading of unlawful content. We may apply usage limits to keep the service running
            for everyone.
          </p>
        </Section>

        <Section title="Availability and warranty">
          <p>
            The service is provided &ldquo;as is&rdquo;, without warranties of any kind. We may
            change, suspend, or discontinue features at any time.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You can stop using Maqraa at any time and request account deletion. We may suspend
            accounts that violate these terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions? Email{" "}
            <a className="text-brand underline" href={`mailto:${CONTACT}`}>
              {CONTACT}
            </a>
            .
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-bold">{title}</h2>
      <div className="mt-2 space-y-2 text-fg-muted">{children}</div>
    </section>
  );
}
