export const ACHIEVEMENTS = [
  {
    slug: "first-steps",
    nameEn: "First Steps",
    nameAr: "الخطوات الأولى",
    description: "Complete your first book.",
    icon: "footprints",
    xpReward: 50,
    criteria: { type: "books_completed", count: 1 },
  },
  {
    slug: "bookworm",
    nameEn: "Bookworm",
    nameAr: "ديدان الكتب",
    description: "Complete 5 books.",
    icon: "book-open",
    xpReward: 150,
    criteria: { type: "books_completed", count: 5 },
  },
  {
    slug: "page-turner",
    nameEn: "Page Turner",
    nameAr: "قَلَّاب الصفحات",
    description: "Log 1,000 pages of reading.",
    icon: "scroll-text",
    xpReward: 150,
    criteria: { type: "pages_logged", count: 1000 },
  },
  {
    slug: "polyglot-vocab",
    nameEn: "Polyglot Vocab",
    nameAr: "متعدد المفردات",
    description: "Graduate 100 vocabulary cards (≥21d interval).",
    icon: "languages",
    xpReward: 200,
    criteria: { type: "vocab_graduated", count: 100 },
  },
  {
    slug: "perfectionist",
    nameEn: "Perfectionist",
    nameAr: "المُتقن",
    description: "Score 100% on 3 comprehension tests.",
    icon: "trophy",
    xpReward: 200,
    criteria: { type: "perfect_tests", count: 3 },
  },
  {
    slug: "week-warrior",
    nameEn: "Week Warrior",
    nameAr: "محارب الأسبوع",
    description: "Maintain a 7-day streak.",
    icon: "flame",
    xpReward: 100,
    criteria: { type: "streak_days", count: 7 },
  },
  {
    slug: "month-marathon",
    nameEn: "Month Marathon",
    nameAr: "ماراثون الشهر",
    description: "Maintain a 30-day streak.",
    icon: "flame",
    xpReward: 500,
    criteria: { type: "streak_days", count: 30 },
  },
  {
    slug: "comeback-kid",
    nameEn: "Comeback Kid",
    nameAr: "العائد",
    description: "Use a streak freeze and keep going.",
    icon: "snowflake",
    xpReward: 50,
    criteria: { type: "freeze_used", count: 1 },
  },
  {
    slug: "genre-hopper",
    nameEn: "Genre Hopper",
    nameAr: "متنقل الأنواع",
    description: "Complete at least one Islamic book, one novel, and one translated work.",
    icon: "shuffle",
    xpReward: 150,
    criteria: { type: "genre_variety" },
  },
  {
    slug: "classical-reader",
    nameEn: "Classical Reader",
    nameAr: "قارئ التراث",
    description: "Complete your first Level 5 book.",
    icon: "scroll",
    xpReward: 250,
    criteria: { type: "level_book_completed", level: 5 },
  },
  {
    slug: "ibn-qayyim-reader",
    nameEn: "Ibn al-Qayyim Reader",
    nameAr: "قارئ ابن القيم",
    description: "Complete any Ibn al-Qayyim work.",
    icon: "book-marked",
    xpReward: 300,
    criteria: { type: "author_completed", author_en: "Ibn al-Qayyim" },
  },
  {
    slug: "night-owl",
    nameEn: "Night Owl",
    nameAr: "بومة الليل",
    description: "Log a session between 22:00 and 04:00.",
    icon: "moon",
    xpReward: 50,
    criteria: { type: "session_time_window", from: 22, to: 4 },
  },
];
