export const ACHIEVEMENTS = [
  {
    slug: "first-steps",
    nameEn: "First Steps",
    nameAr: "الخطوات الأولى",
    description: "Complete your first book.",
    icon: "footprints",
    xpReward: 50,
    criteria: { type: "books_completed", count: 1 },
  },
  {
    slug: "bookworm",
    nameEn: "Bookworm",
    nameAr: "ديدان الكتب",
    description: "Complete 5 books.",
    icon: "book-open",
    xpReward: 150,
    criteria: { type: "books_completed", count: 5 },
  },
  {
    slug: "test-champion",
    nameEn: "Test Champion",
    nameAr: "بطل الاختبارات",
    description: "Pass 5 comprehension tests.",
    icon: "scroll-text",
    xpReward: 150,
    criteria: { type: "tests_passed", count: 5 },
  },
  {
    slug: "polyglot-vocab",
    nameEn: "Polyglot Vocab",
    nameAr: "متعدد المفردات",
    description: "Graduate 100 vocabulary cards (≥21d interval).",
    icon: "languages",
    xpReward: 200,
    criteria: { type: "vocab_graduated", count: 100 },
  },
  {
    slug: "perfectionist",
    nameEn: "Perfectionist",
    nameAr: "المُتقن",
    description: "Score 100% on 2 comprehension tests.",
    icon: "trophy",
    xpReward: 200,
    criteria: { type: "perfect_tests", count: 2 },
  },
  {
    slug: "week-warrior",
    nameEn: "Week Warrior",
    nameAr: "محارب الأسبوع",
    description: "Maintain a 7-day streak.",
    icon: "flame",
    xpReward: 100,
    criteria: { type: "streak_days", count: 7 },
  },
  {
    slug: "month-marathon",
    nameEn: "Month Marathon",
    nameAr: "ماراثون الشهر",
    description: "Maintain a 30-day streak.",
    icon: "flame",
    xpReward: 500,
    criteria: { type: "streak_days", count: 30 },
  },
  {
    slug: "comeback-kid",
    nameEn: "Comeback Kid",
    nameAr: "العائد",
    description: "Use a streak freeze and keep going.",
    icon: "snowflake",
    xpReward: 50,
    criteria: { type: "freeze_used", count: 1 },
  },
  {
    slug: "genre-hopper",
    nameEn: "Genre Hopper",
    nameAr: "متنقل الأنواع",
    description: "Complete at least one Islamic book, one novel, and one translated work.",
    icon: "shuffle",
    xpReward: 150,
    criteria: { type: "genre_variety" },
  },
  {
    slug: "devoted-reader",
    nameEn: "Devoted",
    nameAr: "المُواظِب",
    description: "Maintain a 14-day streak.",
    icon: "flame",
    xpReward: 250,
    criteria: { type: "streak_days", count: 14 },
  },
  {
    slug: "vocab-collector",
    nameEn: "Vocab Collector",
    nameAr: "جامع المفردات",
    description: "Add 50 vocabulary cards to your deck.",
    icon: "languages",
    xpReward: 100,
    criteria: { type: "vocab_count", count: 50 },
  },
];
