export type SeedBook = {
  slug: string;
  level: number;
  orderInLevel: number;
  titleAr: string;
  titleEn: string;
  authorAr?: string;
  authorEn?: string;
  blurb: string;
  difficulty: number; // 1..5 within level
  genre: "islamic" | "arabic_literature" | "translated" | "graded_reader" | "classical";
  isSelection?: boolean;
  recommendedPages?: number;
  hasFullText?: boolean;
};

export const BOOKS: SeedBook[] = [
  /* ─────────────────── Level 1 · Beginner / المبتدئ ─────────────────── */
  {
    slug: "rihlat-samir",
    level: 1,
    orderInLevel: 0,
    titleAr: "رحلة سامر",
    titleEn: "Samir's Journey (Arabic XP Original)",
    authorEn: "Arabic XP Originals",
    blurb:
      "An original fully-diacritized beginner story written for this app. Read it right here — tap any word to translate and save it. Four short chapters about a boy who discovers that every book is a voyage.",
    difficulty: 1,
    genre: "graded_reader",
    recommendedPages: 12,
    hasFullText: true,
  },
  {
    slug: "qasas-al-nabiyeen-lil-atfal",
    level: 1,
    orderInLevel: 1,
    titleAr: "قصص النبيين للأطفال",
    titleEn: "Stories of the Prophets for Children",
    authorAr: "أبو الحسن الندوي",
    authorEn: "Abu al-Hasan al-Nadwi",
    blurb:
      "Vivid, simplified narratives of the prophets in fully harakat-marked Arabic. The classic starting point for every Arabic learner.",
    difficulty: 1,
    genre: "islamic",
    recommendedPages: 300,
  },
  {
    slug: "hikayat-juha",
    level: 1,
    orderInLevel: 2,
    titleAr: "حكايات جحا للأطفال",
    titleEn: "Tales of Juha for Children",
    authorEn: "Various",
    blurb:
      "Short, funny stories of the famous trickster Juha. A staple of every Arab child's bookshelf. Fully diacritized.",
    difficulty: 1,
    genre: "graded_reader",
    recommendedPages: 120,
  },
  {
    slug: "hikayat-aesop-ar",
    level: 1,
    orderInLevel: 3,
    titleAr: "حكايات إيسوب",
    titleEn: "Aesop's Fables",
    authorEn: "Aesop",
    blurb:
      "Short, fully diacritized fables with animals and morals. One per sitting — the smallest possible 'I read a story in Arabic today' win.",
    difficulty: 1,
    genre: "translated",
    recommendedPages: 120,
  },
  {
    slug: "kalila-wa-dimna-lil-nashia",
    level: 1,
    orderInLevel: 4,
    titleAr: "كليلة ودمنة للناشئة",
    titleEn: "Kalila wa Dimna (Adapted for Young Readers)",
    authorAr: "ابن المقفع",
    authorEn: "Ibn al-Muqaffa (adapted)",
    blurb:
      "The classical fables of Kalila wa Dimna, rewritten with harakat and simpler vocabulary. A bridge from kids' books to classical Arabic.",
    difficulty: 2,
    genre: "classical",
    recommendedPages: 160,
  },
  {
    slug: "silsila-dhahabiyya",
    level: 1,
    orderInLevel: 5,
    titleAr: "السلسلة الذهبية للأطفال",
    titleEn: "The Golden Series for Children",
    authorEn: "Various",
    blurb:
      "A long-running Arabic kids' series with short, fully diacritized stories. Pick any volume — each is self-contained.",
    difficulty: 1,
    genre: "graded_reader",
    recommendedPages: 100,
  },

  /* ─────────────────── Level 2 · Starter / البادئ ─────────────────── */
  {
    slug: "diary-wimpy-kid-1-ar",
    level: 2,
    orderInLevel: 1,
    titleAr: "يوميات طالب جبان",
    titleEn: "Diary of a Wimpy Kid",
    authorEn: "Jeff Kinney",
    blurb:
      "Funny, illustrated, and very readable. Modern colloquial-leaning MSA. Perfect for not feeling like you're 'studying'.",
    difficulty: 1,
    genre: "translated",
    recommendedPages: 220,
  },
  {
    slug: "suwar-sahabiyat",
    level: 2,
    orderInLevel: 2,
    titleAr: "صور من حياة الصحابيات",
    titleEn: "Portraits from the Lives of the Female Companions",
    authorAr: "عبد الرحمن رأفت الباشا",
    authorEn: "Abdurrahman Ra'fat al-Basha",
    blurb:
      "Inspirational, easy-flowing stories of women around the Prophet ﷺ. Gentle introduction to Islamic-narrative Arabic.",
    difficulty: 2,
    genre: "islamic",
    recommendedPages: 250,
  },
  {
    slug: "matilda-ar",
    level: 2,
    orderInLevel: 3,
    titleAr: "ماتيلدا",
    titleEn: "Matilda",
    authorEn: "Roald Dahl",
    blurb:
      "Roald Dahl in Arabic. Playful sentences, magical premise. Easy win for an early reader.",
    difficulty: 2,
    genre: "translated",
    recommendedPages: 200,
  },
  {
    slug: "little-prince-ar",
    level: 2,
    orderInLevel: 4,
    titleAr: "الأمير الصغير",
    titleEn: "The Little Prince",
    authorEn: "Antoine de Saint-Exupéry",
    blurb:
      "Short, philosophical, gently profound. Possibly the most translated book on earth. A great early classic.",
    difficulty: 2,
    genre: "translated",
    recommendedPages: 100,
  },

  /* ─────────────────── Level 3 · Walker / السائر ─────────────────── */
  {
    slug: "qiraa-rashida-1",
    level: 3,
    orderInLevel: 1,
    titleAr: "القراءة الراشدة - الجزء الأول",
    titleEn: "The Guided Reader, Vol. 1",
    authorAr: "أبو الحسن الندوي",
    authorEn: "Abu al-Hasan al-Nadwi",
    blurb:
      "Graded Islamic stories and essays designed explicitly for Arabic learners. Smoothest bridge from kids' books to adult prose.",
    difficulty: 1,
    genre: "graded_reader",
    recommendedPages: 200,
  },
  {
    slug: "animal-farm-ar",
    level: 3,
    orderInLevel: 2,
    titleAr: "مزرعة الحيوان",
    titleEn: "Animal Farm",
    authorEn: "George Orwell",
    blurb:
      "Short political allegory. Crisp sentences, finite vocabulary, unforgettable story. A perfect 'I finished a real book' experience.",
    difficulty: 2,
    genre: "translated",
    recommendedPages: 150,
  },
  {
    slug: "kitab-al-tawhid",
    level: 3,
    orderInLevel: 3,
    titleAr: "كتاب التوحيد",
    titleEn: "The Book of Tawhid",
    authorAr: "محمد بن عبد الوهاب",
    authorEn: "Muhammad ibn Abd al-Wahhab",
    blurb:
      "Concise creed in short chapters with hadith and ayat. Foundational and high-repetition vocabulary.",
    difficulty: 2,
    genre: "islamic",
    recommendedPages: 120,
  },
  {
    slug: "arba'in-nawawi",
    level: 3,
    orderInLevel: 4,
    titleAr: "الأربعون النووية",
    titleEn: "The 40 Hadith of al-Nawawi",
    authorAr: "الإمام النووي",
    authorEn: "al-Nawawi",
    blurb:
      "Forty famous hadith. Short, memorizable, and your vocabulary for the rest of your Arabic life. Readable in-app: each hadith is a chapter with tap-to-translate.",
    difficulty: 2,
    genre: "islamic",
    recommendedPages: 80,
    hasFullText: true,
  },
  {
    slug: "old-man-sea-ar",
    level: 3,
    orderInLevel: 5,
    titleAr: "الشيخ والبحر",
    titleEn: "The Old Man and the Sea",
    authorEn: "Ernest Hemingway",
    blurb:
      "Hemingway's spare prose translates beautifully. Short, complete, and oddly affecting.",
    difficulty: 3,
    genre: "translated",
    recommendedPages: 130,
  },
  {
    slug: "qasas-al-arab",
    level: 3,
    orderInLevel: 6,
    titleAr: "قصص العرب",
    titleEn: "Tales of the Arabs",
    authorEn: "Various",
    blurb:
      "Pre-Islamic and early Islamic narratives. Cultural background that makes the rest of Arabic literature click.",
    difficulty: 3,
    genre: "classical",
    recommendedPages: 200,
  },
  {
    slug: "kalila-wa-dimna",
    level: 3,
    orderInLevel: 7,
    titleAr: "كليلة ودمنة",
    titleEn: "Kalila wa Dimna",
    authorAr: "ابن المقفع",
    authorEn: "Abdullah ibn al-Muqaffa'",
    blurb:
      "The 8th-century Arabic classic — Indian fables of clever jackals and noble lions, rendered in Ibn al-Muqaffa's famously elegant prose. Public domain. The first two chapters are readable here.",
    difficulty: 3,
    genre: "classical",
    recommendedPages: 320,
    hasFullText: true,
  },
  {
    slug: "usool-thalatha",
    level: 3,
    orderInLevel: 8,
    titleAr: "الأصول الثلاثة والقواعد الأربع",
    titleEn: "The Three Fundamentals & Four Principles",
    authorAr: "محمد بن عبد الوهاب",
    authorEn: "Muhammad ibn Abd al-Wahhab",
    blurb:
      "Very short, highly memorizable creed primer. Often the first 'real' Arabic Islamic text students study.",
    difficulty: 1,
    genre: "islamic",
    recommendedPages: 60,
  },

  /* ─────────────────── Level 4 · Crosser / العابر ─────────────────── */
  {
    slug: "kitab-al-ilm",
    level: 4,
    orderInLevel: 1,
    titleAr: "كتاب العلم",
    titleEn: "The Book of Knowledge",
    authorAr: "محمد بن صالح العثيمين",
    authorEn: "Muhammad ibn Salih al-Uthaymeen",
    blurb:
      "The virtues of seeking knowledge, the etiquette of the student, and warnings against pride. Clear, modern, accessible.",
    difficulty: 2,
    genre: "islamic",
    recommendedPages: 120,
  },
  {
    slug: "harry-potter-1-ar",
    level: 4,
    orderInLevel: 2,
    titleAr: "هاري بوتر وحجر الفيلسوف",
    titleEn: "Harry Potter and the Philosopher's Stone",
    authorEn: "J.K. Rowling",
    blurb:
      "A whole magical world in Arabic. Vocabulary that's repeated across seven books — investment pays off.",
    difficulty: 3,
    genre: "translated",
    recommendedPages: 320,
  },
  {
    slug: "riyad-as-salihin",
    level: 4,
    orderInLevel: 3,
    titleAr: "رياض الصالحين",
    titleEn: "Gardens of the Righteous",
    authorAr: "الإمام النووي",
    authorEn: "al-Nawawi",
    blurb:
      "The most famous hadith collection. Themed chapters, manageable units, your hadith vocabulary for life.",
    difficulty: 3,
    genre: "islamic",
    recommendedPages: 400,
  },
  {
    slug: "ayyam-1",
    level: 4,
    orderInLevel: 4,
    titleAr: "الأيام - الجزء الأول",
    titleEn: "The Days, Vol. 1",
    authorAr: "طه حسين",
    authorEn: "Taha Hussein",
    blurb:
      "The autobiography of modern Arabic literature's most influential figure. Surprisingly readable; deeply moving.",
    difficulty: 3,
    genre: "arabic_literature",
    recommendedPages: 180,
  },
  {
    slug: "tafsir-saadi-selections",
    level: 4,
    orderInLevel: 5,
    titleAr: "تيسير الكريم الرحمن - مختارات",
    titleEn: "Tafsir al-Saadi (Selections)",
    authorAr: "عبد الرحمن السعدي",
    authorEn: "Abdurrahman al-Saadi",
    blurb:
      "The most accessible classical tafsir. Concise, clear language. Best first tafsir for Arabic readers.",
    difficulty: 3,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 300,
  },
  {
    slug: "fiqh-sunnah-1",
    level: 4,
    orderInLevel: 6,
    titleAr: "فقه السنة - المجلد الأول",
    titleEn: "Fiqh of the Sunnah, Vol. 1",
    authorAr: "السيد سابق",
    authorEn: "Sayyid Sabiq",
    blurb:
      "Clear, well-organized fiqh. Famous for being readable without sacrificing depth. Start with purification.",
    difficulty: 3,
    genre: "islamic",
    recommendedPages: 300,
  },
  {
    slug: "sherlock-holmes-ar",
    level: 4,
    orderInLevel: 7,
    titleAr: "مغامرات شيرلوك هولمز",
    titleEn: "The Adventures of Sherlock Holmes",
    authorEn: "Arthur Conan Doyle",
    blurb:
      "Bite-sized mystery stories. Each one is its own complete arc — easier to push through than a novel.",
    difficulty: 3,
    genre: "translated",
    recommendedPages: 280,
  },
  {
    slug: "bulugh-al-maram",
    level: 4,
    orderInLevel: 8,
    titleAr: "بلوغ المرام من أدلة الأحكام",
    titleEn: "Attainment of the Objective",
    authorAr: "ابن حجر العسقلاني",
    authorEn: "Ibn Hajar al-Asqalani",
    blurb:
      "Hadith arranged by legal topic. Denser than Riyadh as-Salihin, but the natural next step.",
    difficulty: 4,
    genre: "islamic",
    recommendedPages: 350,
  },

  /* ─────────────────── Level 5 · Patient / الصابر ─────────────────── */
  {
    slug: "zad-al-maad-selections",
    level: 5,
    orderInLevel: 1,
    titleAr: "زاد المعاد - مختارات",
    titleEn: "Provisions of the Hereafter (Selections)",
    authorAr: "ابن قيم الجوزية",
    authorEn: "Ibn al-Qayyim",
    blurb:
      "Your first taste of Ibn al-Qayyim's prose. Practical, prophetic, packed with insight.",
    difficulty: 2,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 300,
  },
  {
    slug: "ighathat-al-lahfan",
    level: 5,
    orderInLevel: 2,
    titleAr: "إغاثة اللهفان من مصايد الشيطان",
    titleEn: "Rescue of the Distressed from the Snares of Satan",
    authorAr: "ابن قيم الجوزية",
    authorEn: "Ibn al-Qayyim",
    blurb:
      "Diseases of the heart and their remedies. Semi-autobiographical and accessible Ibn al-Qayyim.",
    difficulty: 3,
    genre: "islamic",
    recommendedPages: 250,
  },
  {
    slug: "zuqaq-al-midaq",
    level: 5,
    orderInLevel: 3,
    titleAr: "زقاق المدق",
    titleEn: "Midaq Alley",
    authorAr: "نجيب محفوظ",
    authorEn: "Naguib Mahfouz",
    blurb:
      "Mahfouz's most readable starting point. A Cairo alley in WW2, a cast you won't forget.",
    difficulty: 3,
    genre: "arabic_literature",
    recommendedPages: 300,
  },
  {
    slug: "1984-ar",
    level: 5,
    orderInLevel: 4,
    titleAr: "1984",
    titleEn: "1984",
    authorEn: "George Orwell",
    blurb:
      "Dystopia in Arabic. The political vocabulary you pick up here is reusable forever.",
    difficulty: 4,
    genre: "translated",
    recommendedPages: 320,
  },
  {
    slug: "aqida-wasitiyyah-sharh",
    level: 5,
    orderInLevel: 5,
    titleAr: "العقيدة الواسطية وشرحها",
    titleEn: "Al-Aqidah al-Wasitiyyah with Commentary",
    authorAr: "ابن تيمية وابن عثيمين",
    authorEn: "Ibn Taymiyyah & al-Uthaymeen",
    blurb:
      "Foundational creed text with al-Uthaymeen's clear commentary. Your bridge to reading Ibn Taymiyyah.",
    difficulty: 4,
    genre: "islamic",
    recommendedPages: 280,
  },
  {
    slug: "ibn-kathir-tafsir-selections",
    level: 5,
    orderInLevel: 6,
    titleAr: "تفسير ابن كثير - مختارات",
    titleEn: "Tafsir Ibn Kathir (Selections)",
    authorAr: "ابن كثير",
    authorEn: "Ibn Kathir",
    blurb:
      "Hadith-based tafsir. Famous, well-organized, and the standard intermediate-level tafsir.",
    difficulty: 4,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 400,
  },
  {
    slug: "rijal-fi-al-shams",
    level: 5,
    orderInLevel: 7,
    titleAr: "رجال في الشمس",
    titleEn: "Men in the Sun",
    authorAr: "غسان كنفاني",
    authorEn: "Ghassan Kanafani",
    blurb:
      "A short, devastating Palestinian novella. Modern Arabic at its most compressed.",
    difficulty: 4,
    genre: "arabic_literature",
    recommendedPages: 100,
  },
  {
    slug: "bidaya-wal-nihaya-selections",
    level: 5,
    orderInLevel: 8,
    titleAr: "البداية والنهاية - مختارات",
    titleEn: "The Beginning and the End (Selections)",
    authorAr: "ابن كثير",
    authorEn: "Ibn Kathir",
    blurb:
      "Islamic history from creation. Start with prophetic narratives; skip the genealogies until later.",
    difficulty: 4,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 400,
  },

  /* ─────────────────── Level 6 · Steadfast / المداوم ─────────────────── */
  {
    slug: "madarij-salikin-selections",
    level: 6,
    orderInLevel: 1,
    titleAr: "مدارج السالكين - مختارات",
    titleEn: "Steps of the Wayfarers (Selections)",
    authorAr: "ابن قيم الجوزية",
    authorEn: "Ibn al-Qayyim",
    blurb:
      "Spiritual stations of the seeker. Ibn al-Qayyim's masterpiece, sampled. Dense but transformative.",
    difficulty: 3,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 400,
  },
  {
    slug: "cairo-trilogy-1",
    level: 6,
    orderInLevel: 2,
    titleAr: "بين القصرين",
    titleEn: "Palace Walk (Cairo Trilogy 1)",
    authorAr: "نجيب محفوظ",
    authorEn: "Naguib Mahfouz",
    blurb:
      "The Nobel-winning trilogy. Slow-burning, social, deeply Arabic. Begin a 1,500-page world.",
    difficulty: 3,
    genre: "arabic_literature",
    recommendedPages: 500,
  },
  {
    slug: "mawsim-al-hijra",
    level: 6,
    orderInLevel: 3,
    titleAr: "موسم الهجرة إلى الشمال",
    titleEn: "Season of Migration to the North",
    authorAr: "الطيب صالح",
    authorEn: "Tayeb Salih",
    blurb:
      "Arabic literature's most studied modern novel. Short, layered, postcolonial.",
    difficulty: 4,
    genre: "arabic_literature",
    recommendedPages: 200,
  },
  {
    slug: "mukhtasar-minhaj-sunna",
    level: 6,
    orderInLevel: 4,
    titleAr: "مختصر منهاج السنة النبوية",
    titleEn: "Abridged Way of the Prophetic Sunnah",
    authorAr: "ابن تيمية",
    authorEn: "Ibn Taymiyyah",
    blurb:
      "Theological polemic against extremism. Requires strong classical grammar. Your first real Ibn Taymiyyah.",
    difficulty: 5,
    genre: "islamic",
    recommendedPages: 300,
  },
  {
    slug: "muwafaqat-1",
    level: 6,
    orderInLevel: 5,
    titleAr: "الموافقات - الجزء الأول",
    titleEn: "Al-Muwafaqat, Vol. 1",
    authorAr: "الإمام الشاطبي",
    authorEn: "al-Shatibi",
    blurb:
      "The classical text on the higher objectives of Islamic law. Theoretical and demanding.",
    difficulty: 5,
    genre: "islamic",
    recommendedPages: 350,
  },
  {
    slug: "brothers-karamazov-ar",
    level: 6,
    orderInLevel: 6,
    titleAr: "الإخوة كرامازوف",
    titleEn: "The Brothers Karamazov",
    authorEn: "Fyodor Dostoevsky",
    blurb:
      "The deepest novel ever written, in Arabic. Long, philosophical, theological. A serious mountain.",
    difficulty: 5,
    genre: "translated",
    recommendedPages: 900,
  },

  /* ─────────────────── Level 7 · Rooted / الراسخ ─────────────────── */
  {
    slug: "madarij-salikin-full",
    level: 7,
    orderInLevel: 1,
    titleAr: "مدارج السالكين كاملاً",
    titleEn: "Steps of the Wayfarers (Complete)",
    authorAr: "ابن قيم الجوزية",
    authorEn: "Ibn al-Qayyim",
    blurb:
      "All three volumes. Ibn al-Qayyim at full force. A lifetime book.",
    difficulty: 3,
    genre: "islamic",
    recommendedPages: 1200,
  },
  {
    slug: "majmu-fatawa-selections-1",
    level: 7,
    orderInLevel: 2,
    titleAr: "مجموع الفتاوى - المجلدات 1-5 مختارات",
    titleEn: "Majmu' al-Fatawa, Vols. 1–5 (Selections)",
    authorAr: "ابن تيمية",
    authorEn: "Ibn Taymiyyah",
    blurb:
      "Curated thematic selections from Ibn Taymiyyah's monumental compilation. The real thing.",
    difficulty: 5,
    genre: "islamic",
    isSelection: true,
    recommendedPages: 500,
  },
  {
    slug: "bukhala-jahiz",
    level: 7,
    orderInLevel: 3,
    titleAr: "البخلاء",
    titleEn: "The Misers",
    authorAr: "الجاحظ",
    authorEn: "al-Jahiz",
    blurb:
      "Classical Arabic literature's funniest book. Anecdotes about misers, masterful prose.",
    difficulty: 4,
    genre: "classical",
    recommendedPages: 300,
  },
  {
    slug: "tafsir-ibn-kathir-full",
    level: 7,
    orderInLevel: 4,
    titleAr: "تفسير ابن كثير كاملاً",
    titleEn: "Tafsir Ibn Kathir (Complete)",
    authorAr: "ابن كثير",
    authorEn: "Ibn Kathir",
    blurb:
      "The full hadith-based tafsir. The reference book of your reading life.",
    difficulty: 4,
    genre: "islamic",
    recommendedPages: 3000,
  },
  {
    slug: "darwish-diwan",
    level: 7,
    orderInLevel: 5,
    titleAr: "ديوان محمود درويش",
    titleEn: "The Collected Poems of Mahmoud Darwish",
    authorAr: "محمود درويش",
    authorEn: "Mahmoud Darwish",
    blurb:
      "Modern Arabic poetry's most loved voice. Read slowly; read aloud.",
    difficulty: 5,
    genre: "arabic_literature",
    recommendedPages: 600,
  },

  /* ─────────────────── Level 8 · Established / المتمكن ─────────────────── */
  {
    slug: "majmu-fatawa-full",
    level: 8,
    orderInLevel: 1,
    titleAr: "مجموع الفتاوى كاملاً",
    titleEn: "Majmu' al-Fatawa (Complete)",
    authorAr: "ابن تيمية",
    authorEn: "Ibn Taymiyyah",
    blurb:
      "All 37 volumes. A lifetime's reference and a Mount Everest of classical Arabic scholarship.",
    difficulty: 5,
    genre: "islamic",
    recommendedPages: 18000,
  },
  {
    slug: "tafsir-tabari-full",
    level: 8,
    orderInLevel: 2,
    titleAr: "تفسير الطبري كاملاً",
    titleEn: "Tafsir al-Tabari (Complete)",
    authorAr: "الإمام الطبري",
    authorEn: "al-Tabari",
    blurb:
      "The earliest comprehensive tafsir. Linguistic, variant readings, chains. The mother text.",
    difficulty: 5,
    genre: "islamic",
    recommendedPages: 15000,
  },
  {
    slug: "diwan-mutanabbi",
    level: 8,
    orderInLevel: 3,
    titleAr: "ديوان المتنبي",
    titleEn: "The Diwan of al-Mutanabbi",
    authorAr: "أبو الطيب المتنبي",
    authorEn: "al-Mutanabbi",
    blurb:
      "The greatest Arabic poet. Demanding, glorious, foundational.",
    difficulty: 5,
    genre: "classical",
    recommendedPages: 800,
  },
  {
    slug: "maqamat-hariri",
    level: 8,
    orderInLevel: 4,
    titleAr: "مقامات الحريري",
    titleEn: "The Maqamat of al-Hariri",
    authorAr: "بديع الزمان الحريري",
    authorEn: "al-Hariri",
    blurb:
      "Rhymed prose virtuosity. The benchmark of Arabic literary skill for a thousand years.",
    difficulty: 5,
    genre: "classical",
    recommendedPages: 500,
  },
  {
    slug: "alf-layla-full",
    level: 8,
    orderInLevel: 5,
    titleAr: "ألف ليلة وليلة",
    titleEn: "One Thousand and One Nights",
    blurb:
      "The complete original-language text. A lifetime of stories, classical Arabic at its most playful.",
    difficulty: 4,
    genre: "classical",
    recommendedPages: 3000,
  },

  /* ─────────────────── Level 9 · Seeker of Knowledge / طالب العلم ─────────────────── */
  {
    slug: "seeker-parallel-tafsir",
    level: 9,
    orderInLevel: 1,
    titleAr: "تفاسير القرآن متوازية",
    titleEn: "Parallel Tafsir Study",
    blurb:
      "Reading al-Tabari, al-Qurtubi, Ibn Kathir, and al-Saadi side by side. Lifetime work.",
    difficulty: 5,
    genre: "islamic",
  },
  {
    slug: "seeker-sibawayh",
    level: 9,
    orderInLevel: 2,
    titleAr: "الكتاب",
    titleEn: "Al-Kitab",
    authorAr: "سيبويه",
    authorEn: "Sibawayh",
    blurb:
      "The foundational text of Arabic grammar. The grammar book all grammar books reference.",
    difficulty: 5,
    genre: "classical",
  },
  {
    slug: "seeker-classical-corpus",
    level: 9,
    orderInLevel: 3,
    titleAr: "أمهات الكتب",
    titleEn: "The Mother Books",
    blurb:
      "Engagement with critical editions, manuscript traditions, and the foundational classical corpus across genres.",
    difficulty: 5,
    genre: "classical",
  },
];
