/**
 * High-frequency Arabic words served instantly on tap — no AI call, no network.
 * Keyed by the de-diacritized `lookupKey` so they match regardless of how the
 * source text is vocalized. Deliberately limited to common, unambiguous function
 * words and very frequent vocabulary; everything else falls back to the AI lookup.
 */
export type CommonEntry = { lemma_ar: string; gloss_en: string; pos: string };

export const COMMON_WORDS: Record<string, CommonEntry> = {
  // prepositions & particles
  "في": { lemma_ar: "فِي", gloss_en: "in, at", pos: "preposition" },
  "من": { lemma_ar: "مِنْ", gloss_en: "from; who", pos: "preposition / pronoun" },
  "إلى": { lemma_ar: "إِلَى", gloss_en: "to, towards", pos: "preposition" },
  "على": { lemma_ar: "عَلَى", gloss_en: "on, upon", pos: "preposition" },
  "عن": { lemma_ar: "عَنْ", gloss_en: "about, from", pos: "preposition" },
  "مع": { lemma_ar: "مَعَ", gloss_en: "with", pos: "preposition" },
  "عند": { lemma_ar: "عِنْدَ", gloss_en: "at, by, with", pos: "preposition" },
  "بعد": { lemma_ar: "بَعْدَ", gloss_en: "after", pos: "preposition" },
  "قبل": { lemma_ar: "قَبْلَ", gloss_en: "before", pos: "preposition" },
  "تحت": { lemma_ar: "تَحْتَ", gloss_en: "under, below", pos: "preposition" },
  "فوق": { lemma_ar: "فَوْقَ", gloss_en: "above, over", pos: "preposition" },
  "بين": { lemma_ar: "بَيْنَ", gloss_en: "between, among", pos: "preposition" },
  "حول": { lemma_ar: "حَوْلَ", gloss_en: "around", pos: "preposition" },
  "نحو": { lemma_ar: "نَحْوَ", gloss_en: "towards", pos: "preposition" },
  "حتى": { lemma_ar: "حَتَّى", gloss_en: "until, even", pos: "particle" },
  "إلا": { lemma_ar: "إِلَّا", gloss_en: "except, but", pos: "particle" },
  "لكن": { lemma_ar: "لَكِنْ", gloss_en: "but", pos: "conjunction" },
  "أو": { lemma_ar: "أَوْ", gloss_en: "or", pos: "conjunction" },
  "ثم": { lemma_ar: "ثُمَّ", gloss_en: "then", pos: "conjunction" },
  "إذا": { lemma_ar: "إِذَا", gloss_en: "if, when", pos: "particle" },
  "إذ": { lemma_ar: "إِذْ", gloss_en: "when, since", pos: "particle" },
  "قد": { lemma_ar: "قَدْ", gloss_en: "indeed; perhaps", pos: "particle" },
  "لقد": { lemma_ar: "لَقَدْ", gloss_en: "indeed (emphatic)", pos: "particle" },
  "لم": { lemma_ar: "لَمْ", gloss_en: "did not", pos: "particle" },
  "لن": { lemma_ar: "لَنْ", gloss_en: "will not", pos: "particle" },
  "لا": { lemma_ar: "لَا", gloss_en: "no, not", pos: "particle" },
  "ما": { lemma_ar: "مَا", gloss_en: "what; not", pos: "particle / pronoun" },
  "هل": { lemma_ar: "هَلْ", gloss_en: "(question particle)", pos: "particle" },
  "أن": { lemma_ar: "أَنْ", gloss_en: "to, that", pos: "particle" },
  "إن": { lemma_ar: "إِنَّ", gloss_en: "indeed; if", pos: "particle" },
  "بل": { lemma_ar: "بَلْ", gloss_en: "rather, but", pos: "particle" },
  "نعم": { lemma_ar: "نَعَمْ", gloss_en: "yes", pos: "particle" },
  "لو": { lemma_ar: "لَوْ", gloss_en: "if (hypothetical)", pos: "particle" },
  "كي": { lemma_ar: "كَيْ", gloss_en: "so that", pos: "particle" },
  "أيضا": { lemma_ar: "أَيْضًا", gloss_en: "also, too", pos: "adverb" },
  "جدا": { lemma_ar: "جِدًّا", gloss_en: "very", pos: "adverb" },
  "الآن": { lemma_ar: "الْآنَ", gloss_en: "now", pos: "adverb" },
  "هنا": { lemma_ar: "هُنَا", gloss_en: "here", pos: "adverb" },
  "هناك": { lemma_ar: "هُنَاكَ", gloss_en: "there", pos: "adverb" },

  // pronouns & demonstratives
  "هو": { lemma_ar: "هُوَ", gloss_en: "he, it", pos: "pronoun" },
  "هي": { lemma_ar: "هِيَ", gloss_en: "she, it", pos: "pronoun" },
  "هم": { lemma_ar: "هُمْ", gloss_en: "they (m.)", pos: "pronoun" },
  "هن": { lemma_ar: "هُنَّ", gloss_en: "they (f.)", pos: "pronoun" },
  "أنا": { lemma_ar: "أَنَا", gloss_en: "I", pos: "pronoun" },
  "أنت": { lemma_ar: "أَنْتَ", gloss_en: "you", pos: "pronoun" },
  "نحن": { lemma_ar: "نَحْنُ", gloss_en: "we", pos: "pronoun" },
  "هذا": { lemma_ar: "هَذَا", gloss_en: "this (m.)", pos: "demonstrative" },
  "هذه": { lemma_ar: "هَذِهِ", gloss_en: "this (f.)", pos: "demonstrative" },
  "ذلك": { lemma_ar: "ذَلِكَ", gloss_en: "that (m.)", pos: "demonstrative" },
  "تلك": { lemma_ar: "تِلْكَ", gloss_en: "that (f.)", pos: "demonstrative" },
  "هؤلاء": { lemma_ar: "هَؤُلَاءِ", gloss_en: "these", pos: "demonstrative" },
  "الذي": { lemma_ar: "الَّذِي", gloss_en: "who, which (m.)", pos: "relative pronoun" },
  "التي": { lemma_ar: "الَّتِي", gloss_en: "who, which (f.)", pos: "relative pronoun" },
  "الذين": { lemma_ar: "الَّذِينَ", gloss_en: "who (pl.)", pos: "relative pronoun" },
  "كل": { lemma_ar: "كُلّ", gloss_en: "all, every", pos: "noun" },
  "بعض": { lemma_ar: "بَعْض", gloss_en: "some", pos: "noun" },

  // very common verbs (incl. frequent inflections)
  "كان": { lemma_ar: "كَانَ", gloss_en: "to be, was", pos: "verb" },
  "كانت": { lemma_ar: "كَانَ", gloss_en: "she/it was", pos: "verb" },
  "يكون": { lemma_ar: "كَانَ", gloss_en: "to be", pos: "verb" },
  "ليس": { lemma_ar: "لَيْسَ", gloss_en: "is not", pos: "verb" },
  "قال": { lemma_ar: "قَالَ", gloss_en: "to say, said", pos: "verb" },
  "قالت": { lemma_ar: "قَالَ", gloss_en: "she said", pos: "verb" },
  "يقول": { lemma_ar: "قَالَ", gloss_en: "to say", pos: "verb" },
  "جاء": { lemma_ar: "جَاءَ", gloss_en: "to come, came", pos: "verb" },
  "ذهب": { lemma_ar: "ذَهَبَ", gloss_en: "to go, went", pos: "verb" },
  "رأى": { lemma_ar: "رَأَى", gloss_en: "to see, saw", pos: "verb" },
  "أراد": { lemma_ar: "أَرَادَ", gloss_en: "to want", pos: "verb" },
  "وجد": { lemma_ar: "وَجَدَ", gloss_en: "to find", pos: "verb" },
  "أخذ": { lemma_ar: "أَخَذَ", gloss_en: "to take", pos: "verb" },
  "جعل": { lemma_ar: "جَعَلَ", gloss_en: "to make, put", pos: "verb" },
  "صار": { lemma_ar: "صَارَ", gloss_en: "to become", pos: "verb" },

  // very common nouns
  "الله": { lemma_ar: "اللّٰه", gloss_en: "God, Allah", pos: "noun" },
  "يوم": { lemma_ar: "يَوْم", gloss_en: "day", pos: "noun" },
  "ليلة": { lemma_ar: "لَيْلَة", gloss_en: "night", pos: "noun" },
  "الناس": { lemma_ar: "النَّاس", gloss_en: "the people", pos: "noun" },
  "رجل": { lemma_ar: "رَجُل", gloss_en: "man", pos: "noun" },
  "امرأة": { lemma_ar: "اِمْرَأَة", gloss_en: "woman", pos: "noun" },
  "ولد": { lemma_ar: "وَلَد", gloss_en: "boy, child", pos: "noun" },
  "بيت": { lemma_ar: "بَيْت", gloss_en: "house", pos: "noun" },
  "مدينة": { lemma_ar: "مَدِينَة", gloss_en: "city", pos: "noun" },
  "كتاب": { lemma_ar: "كِتَاب", gloss_en: "book", pos: "noun" },
  "ماء": { lemma_ar: "مَاء", gloss_en: "water", pos: "noun" },
  "يد": { lemma_ar: "يَد", gloss_en: "hand", pos: "noun" },
  "قلب": { lemma_ar: "قَلْب", gloss_en: "heart", pos: "noun" },
  "نفس": { lemma_ar: "نَفْس", gloss_en: "self, soul", pos: "noun" },
  "أمر": { lemma_ar: "أَمْر", gloss_en: "matter, command", pos: "noun" },
  "شيء": { lemma_ar: "شَيْء", gloss_en: "thing", pos: "noun" },
  "اسم": { lemma_ar: "اِسْم", gloss_en: "name", pos: "noun" },
  "ابن": { lemma_ar: "اِبْن", gloss_en: "son", pos: "noun" },
  "رسول": { lemma_ar: "رَسُول", gloss_en: "messenger", pos: "noun" },
  "سنة": { lemma_ar: "سَنَة", gloss_en: "year", pos: "noun" },
  "مرة": { lemma_ar: "مَرَّة", gloss_en: "time, once", pos: "noun" },
  "طريق": { lemma_ar: "طَرِيق", gloss_en: "road, way", pos: "noun" },
  "باب": { lemma_ar: "بَاب", gloss_en: "door, gate", pos: "noun" },

  // common adjectives
  "كبير": { lemma_ar: "كَبِير", gloss_en: "big, large", pos: "adjective" },
  "صغير": { lemma_ar: "صَغِير", gloss_en: "small", pos: "adjective" },
  "جديد": { lemma_ar: "جَدِيد", gloss_en: "new", pos: "adjective" },
  "قديم": { lemma_ar: "قَدِيم", gloss_en: "old", pos: "adjective" },
  "جميل": { lemma_ar: "جَمِيل", gloss_en: "beautiful", pos: "adjective" },
  "كثير": { lemma_ar: "كَثِير", gloss_en: "much, many", pos: "adjective" },
  "قليل": { lemma_ar: "قَلِيل", gloss_en: "few, little", pos: "adjective" },
  "طويل": { lemma_ar: "طَوِيل", gloss_en: "long, tall", pos: "adjective" },
  "قصير": { lemma_ar: "قَصِير", gloss_en: "short", pos: "adjective" },
};
